index:
  path: /
  controller: App\Controller\HomeController::index

creation:
  path: /creation
  controller: App\Controller\HomeController::creation

who:
  path: /index/who
  controller: App\Controller\HomeController::who    

seo:
  path: /seo
  controller: App\Controller\HomeController::seo

products:
  path: /products
  controller: App\Controller\HomeController::products

host:
  path: /host
  controller: App\Controller\HomeController::host

portfolio:
  path: /portfolio
  controller: App\Controller\HomeController::portfolio

accomodation:
  path: /host/accomodation
  controller: App\Controller\HomeController::accomodation

registration:
  path: /host/registration
  controller: App\Controller\HomeController::registration

development:
  path: /creation/development
  controller: App\Controller\HomeController::development

translation:
  path: /translation/{lang}/{page}
  controller: App\Controller\HomeController::userTranslation

terms:
  path: /terms
  controller: App\Controller\HomeController::terms

safePayment:
  path: /safePayment
  controller: App\Controller\HomeController::safePayment

deliveries:
  path: /deliveries
  controller: App\Controller\HomeController::deliveries

map:
  path: /map
  controller: App\Controller\HomeController::map

weCall:
  path: /weCall
  controller: App\Controller\HomeController::weCall

contacts:
  path: /contacts
  controller: App\Controller\HomeController::contacts

errorForm:
  path: /errorForm
  controller: App\Controller\HomeController::errorForm

footer:
  path: /footer
  controller: App\Controller\HomeController::footer